#pragma once

#define IDI_APP_ICON 101
#define IDI_TOOLBAR_RECORD 201
#define IDI_TOOLBAR_PAUSE 202
#define IDI_TOOLBAR_SIZE 203
#define IDI_TOOLBAR_SOUND 204
#define IDI_TOOLBAR_OPEN 205
#define IDI_TOOLBAR_STOP 206
